### ISSUE TITLE
Program won't run on windows server 2019

### ISSUE THREAD

**Issue by mattksand** [Kentico/ADImport#24]
I have installed version 13 of this app on 3 different windows servers and the program won't run. It does however run on my own personal windows machine. All servers all have .net frame work of 4.8 installed. All have kentico installations already running on the server with no issue.

**I get the same error on each server:
Application Error:**
Log Name:      Application
Source:        Application Error
Date:          3/4/2021 10:28:52 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      us-bks-web-d-01.brooks.com
Descrip tion:
Faulting application name: ADImport.exe, version: 13.0.0.0, time stamp: 0x5fabf75a
Faulting module name: KERNELBASE.dll, version: 10.0.17763.1697, time stamp: 0xb157f7ff
Exception code: 0xe0434352
Fault offset: 0x00000000000396c9
Faulting process id: 0x39e4
Faulting application start time: 0x01d71145c0c03560
Faulting application path: C:\Users\3mstone\Desktop\ADImport-v13.0.0\ADImport.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: dc1a0f34-6e91-42f1-9e69-298a817d515b
Faulting package full name:
Faulting package-relative application ID:
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-03-04T22:28:52.089259900Z" />
    <EventRecordID>24433</EventRecordID>
    <Channel>Application</Channel>
    <Computer>us-bks-web-d-01.brooks.com</Computer>
    <Security />
  </System>
  <EventData>
    <Data>ADImport.exe</Data>
    <Data>13.0.0.0</Data>
    <Data>5fabf75a</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.17763.1697</Data>
    <Data>b157f7ff</Data>
    <Data>e0434352</Data>
    <Data>00000000000396c9</Data>
    <Data>39e4</Data>
    <Data>01d71145c0c03560</Data>
    <Data>C:\Users\3mstone\Desktop\ADImport-v13.0.0\ADImport.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>dc1a0f34-6e91-42f1-9e69-298a817d515b</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**.net runtime**
Log Name:      Application
Source:        .NET Runtime
Date:          3/4/2021 10:28:51 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      us-bks-web-d-01.brooks.com
Descrip tion:
Application: ADImport.exe
Framework Version: v4.0.30319
Descrip tion: The process was terminated due to an unhandled exception.
Exception Info: System.NotSupportedException

Exception Info: System.IO.FileLoadException
   at System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.Assembly.Load(System.Reflection.AssemblyName)
   at CMS.Core.AssemblyDiscovery.AddAssembly(System.Collections.Generic.ICollection`1<System.Reflection.Assembly>, System.Reflection.AssemblyName)
   at CMS.Core.AssemblyDiscovery.AddOnlyDiscoverableAssembly(System.Collections.Generic.ICollection`1<System.Reflection.Assembly>, System.Collections.Generic.Dictionary`2<System.String,System.Reflection.Assembly>, System.Reflection.AssemblyName, System.String)
   at CMS.Core.AssemblyDiscovery.ExecuteGetAssemblies(Boolean)
   at CMS.Core.AssemblyDiscovery.get_DiscoverableAssemblies()
   at CMS.Core.AssemblyDiscoveryHelper.GetAssemblies(Boolean)
   at CMS.Core.ModuleDiscovery.GetModules()
   at CMS.Core.ModuleEntryManager.GetDiscoverableModules()
   at CMS.Core.ModuleEntryManager.ModuleCollectionsInitialization()
   at CMS.Core.ModuleEntryManager.PreInit()
   at CMS.Core.AppCore.PreInit()
   at CMS.DataEngine.CMSApplication.PreInit(Boolean)
   at ADImport.Program.Main(System.String[])

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-03-04T22:28:51.902263000Z" />
    <EventRecordID>24432</EventRecordID>
    <Channel>Application</Channel>
    <Computer>us-bks-web-d-01.brooks.com</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: ADImport.exe
Framework Version: v4.0.30319
Descrip tion: The process was terminated due to an unhandled exception.
Exception Info: System.NotSupportedException

Exception Info: System.IO.FileLoadException
   at System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.Assembly.Load(System.Reflection.AssemblyName)
   at CMS.Core.AssemblyDiscovery.AddAssembly(System.Collections.Generic.ICollection`1&lt;System.Reflection.Assembly&gt;, System.Reflection.AssemblyName)
   at CMS.Core.AssemblyDiscovery.AddOnlyDiscoverableAssembly(System.Collections.Generic.ICollection`1&lt;System.Reflection.Assembly&gt;, System.Collections.Generic.Dictionary`2&lt;System.String,System.Reflection.Assembly&gt;, System.Reflection.AssemblyName, System.String)
   at CMS.Core.AssemblyDiscovery.ExecuteGetAssemblies(Boolean)
   at CMS.Core.AssemblyDiscovery.get_DiscoverableAssemblies()
   at CMS.Core.AssemblyDiscoveryHelper.GetAssemblies(Boolean)
   at CMS.Core.ModuleDiscovery.GetModules()
   at CMS.Core.ModuleEntryManager.GetDiscoverableModules()
   at CMS.Core.ModuleEntryManager.ModuleCollectionsInitialization()
   at CMS.Core.ModuleEntryManager.PreInit()
   at CMS.Core.AppCore.PreInit()
   at CMS.DataEngine.CMSApplication.PreInit(Boolean)
   at ADImport.Program.Main(System.String[])

</Data>
  </EventData>
</Event>

**Comment by yuriys-kentico** [comment]
We found that it needed the following DLLs from a normal Kentico Xperience 13 installation in order to run successfully:
```
CMS.Activities, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.Activities.Loggers, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.AmazonStorage, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.AspNet.Platform, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.Automation, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.AzureStorage, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.ContactManagement, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.ContinuousIntegration, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.CustomTables, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.DataProtection, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.DocumentEngine, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.Ecommerce, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.EmailEngine, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.EventLog, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.FormEngine, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.Globalization, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.Helpers, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.ImportExport, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.LicenseProvider, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.MacroEngine, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.MediaLibrary, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.Membership, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.MembershipProvider, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.Modules, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.Newsletters, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.OnlineForms, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.OnlineMarketing, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.Personas, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.Relationships, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.Reporting, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.ResponsiveImages, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.Routing.Web, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.SalesForce, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.Scheduler, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.Search.Azure, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.Search, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.Search.Lucene3, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.Search.TextExtractors, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.SharePoint, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.SiteProvider, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.SocialMarketing, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.Synchronization, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.SynchronizationEngine, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.Taxonomy, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.TranslationServices, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.WebAnalytics, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.WebFarmSync, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
CMS.WorkflowEngine, Version=13.0.0.0, Culture=neutral, PublicKeyToken=834b12a258f213f9
```

**Comment by themooserooster** [comment]
I'm getting this problem too. Still happening on Windows 10 in multiple environments.

**Comment by themooserooster** [comment]
Can confirm using DLLs from a clean CMS admin instance resolve the issue. Can a maintainer please do a release with updated DLLs?

**Comment by sxm0275** [comment]
I am having exact same issue with version 13 not running on our Windows 16 web servers but runs fine on my Windows 10 local machine. I also tried copying the dlls from CMS and that didn't work either. Can anyone please share the solution if this issue has been resolved? Any help or suggestions would be appreciated. 

Error:
Application: ADImport.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NotSupportedException

Exception Info: System.IO.FileLoadException
   at System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.Assembly.Load(System.Reflection.AssemblyName)
   at CMS.Core.AssemblyDiscovery.AddAssembly(System.Collections.Generic.ICollection`1<System.Reflection.Assembly>, System.Reflection.AssemblyName)
   at CMS.Core.AssemblyDiscovery.AddOnlyDiscoverableAssembly(System.Collections.Generic.ICollection`1<System.Reflection.Assembly>, System.Collections.Generic.Dictionary`2<System.String,System.Reflection.Assembly>, System.Reflection.AssemblyName, System.String)
   at CMS.Core.AssemblyDiscovery.ExecuteGetAssemblies(Boolean)
   at CMS.Core.AssemblyDiscovery.get_DiscoverableAssemblies()
   at CMS.Core.AssemblyDiscoveryHelper.GetAssemblies(Boolean)
   at CMS.Core.ModuleDiscovery.GetModules()
   at CMS.Core.ModuleEntryManager.GetDiscoverableModules()
   at CMS.Core.ModuleEntryManager.ModuleCollectionsInitialization()
   at CMS.Core.ModuleEntryManager.PreInit()
   at CMS.Core.AppCore.PreInit()
   at CMS.DataEngine.CMSApplication.PreInit(Boolean)
   at ADImport.Program.Main(System.String[])
