### ISSUE TITLE
Kentico AD Import Utilty query

### ISSUE THREAD

**Issue by spwatsondit** [Kentico/ADImport#7]
UPDATE 03/08/2016 16:24PM GMT

We have made some updates to our database in relation to the users and roles, but we are now seeing another message from the AD import process.  I have created a new issue for this.

Kind regards,

Stephen Watson

Hi,

I'm not sure if you are the correct contact to approach about this issue, but we are currently using the Kentico Active Directory Import Utility to import users from a remote server into a Kentico website, but when we run the import we are seeing following error:

[2017-08-02 15:17:36] Error occurredMessage: The server is not operational.

Stack Trace: 
   at System.DirectoryServices.AccountManagement.ADStoreCtx.FindPrincipalByIdentRefHelper(Type principalType, String urnScheme, String urnValue, DateTime referenceDate, Boolean useSidHistory)
   at System.DirectoryServices.AccountManagement.ADStoreCtx.FindPrincipalByIdentRef(Type principalType, String urnScheme, String urnValue, DateTime referenceDate)
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithTypeHelper(PrincipalContext context, Type principalType, Nullable`1 identityType, String identityValue, DateTime refDate)
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, IdentityType identityType, String identityValue)
   at ADImport.ADProvider.Exists(Object objectIdentifier) in D:\ADImport-10.0.0\ADImport-10.0.0\ADImport\ADProvider.cs:line 1414
   at lambda_method(Closure , RoleInfo )
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at ADImport.CMSImport.DeleteNonExistingObjects(CumulatedChanges usersChanged, CumulatedChanges rolesChanged) in D:\ADImport-10.0.0\ADImport-10.0.0\ADImport\CMSImport.cs:line 980
   at ADImport.CMSImport.ImportWorker_DoWork(Object sender, DoWorkEventArgs e) in D:\ADImport-10.0.0\ADImport-10.0.0\ADImport\CMSImport.cs:line 368
The server is not operational.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.DirectorySearcher.FindAll(Boolean findMoreThanOne)
   at System.DirectoryServices.AccountManagement.ADStoreCtx.FindPrincipalByIdentRefHelper(Type principalType, String urnScheme, String urnValue, DateTime referenceDate, Boolean useSidHistory)

Looking through the code, it seems to be breaking in the ADImport.cs at line 980 (the code extract has been attached), which seems to be the point where the deletion of CMS (domain) roles that do not exist in AD anymore.  The utility can connect to the remote server fine, so we can select the user groups and users to import, but when attempting the import itself, it shows the above message.

Is this something you can help with?

Thank you.

Kind regards,

Stephen Watson
Discover IT UK

[CMSImport.zip](https://github.com/Kentico/ADImport/files/1196803/CMSImport.zip)

**Comment by petrsvihlik** [comment]
@MarecekF @ZdenekS81 Can you guys please make someone from the platform team have a look?

**Comment by spwatsondit** [comment]
Hi,

Are there any suggestions for the query I have entered here?  We need to find a solution for this, thank you.

Kind regards,

Stephen

**Comment by petrsvihlik** [comment]
Hi, afaik @ZdenekS81 is on it... let's wait for an update from him.

**Comment by ZdenekS81** [comment]
Hi Stephen,

are errors from your comments still present or have you been able to solve them, please?

Best regards,
Zdenek
